[changelog]
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}
"""
trim = true
render_always = true

[git]
conventional_commits = true
filter_unconventional = true
require_conventional = false
split_commits = false
protect_breaking_commits = false
commit_parsers = [
    { message = "^chore: bump to", skip = true },
    { message = "^chore\\(release\\): prepare for", skip = true },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^feat", group = "<!-- 00 -->🚀 Features" },
    { message = "^fix", group = "<!-- 01 -->🐛 Bug Fixes" },
    { body = ".*security", group = "<!-- 02 -->🛡️ Security" },
    { message = "^perf", group = "<!-- 03 -->⚡ Performance" },
    { message = "^refactor", group = "<!-- 04 -->🚜 Refactor" },
    { message = "^style", group = "<!-- 05 -->🎨 Styling" },
    { message = "^doc", group = "<!-- 06 -->📚 Documentation" },
    { message = "^translate", group = "<!-- 07 -->🌍 Translations" },
    { message = "^test", group = "<!-- 08 -->🧪 Testing" },
    { message = "^chore|^ci", group = "<!-- 09 -->⚙️ Miscellaneous Tasks" },
    { message = "^revert", group = "<!-- 10 -->◀️ Revert" },
    { message = ".*", group = "<!-- 11 -->💼 Other" },
]
filter_commits = false
fail_on_unmatched_commit = false
use_branch_tags = false
topo_order = false
topo_order_commits = true
sort_commits = "oldest"
recurse_submodules = false
