[versions]
agp = "9.4.0"
android-compileSdk = "37"
android-minSdk = "27"
androidx-composeBom = "2026.09.00"
androidx-navigationCompose = "2.10.1"
compose-material3 = "1.9.0"
compose-materialIconsExtended = "1.7.3"
compose-multiplatform = "1.12.0"
kotlin = "2.4.20"
kotlinx-coroutinesSwing = "1.11.0"
kotlinx-serializationJson = "1.11.0"
zip4j = "2.11.6"

[libraries]
androidx-composeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-composeBom" }
androidx-navigationCompose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigationCompose" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-materialIconsExtended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "compose-materialIconsExtended" }
compose-uiTooling = { group = "org.jetbrains.compose.ui", name = "ui-tooling", version.ref = "compose-multiplatform" }
compose-uiToolingPreview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "compose-multiplatform" }
kotlinx-coroutinesSwing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutinesSwing" }
kotlinx-serializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serializationJson" }
zip4j = { group = "net.lingala.zip4j", name = "zip4j", version.ref = "zip4j" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-multiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }