name: Build Desktop

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest

  workflow_dispatch:
    inputs:
      os:
        required: true
        type: string
        default: ubuntu-latest
        description: Operating System

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 21
      - name: Build Package
        run: |
          chmod +x ./gradlew
          ./gradlew clean desktopApp:packageReleaseDistributionForCurrentOS
          for dir in desktopApp/build/compose/binaries/main-release/*/; do
            ext=$(basename "$dir")
            for file in "$dir"*."$ext"; do
              if [ -e "$file" ]; then
                path="openbible-desktop.$ext"
                echo "path=$path" >> $GITHUB_ENV
                mv "$file" "$path"
                break 2
              fi
            done
          done
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.path }}
          path: ${{ env.path }}
