name: Build Desktop

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest

  workflow_dispatch:
    inputs:
      os:
        required: true
        type: string
        default: ubuntu-latest
        description: Operating System

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 21
      - name: Build Package (macOS/Linux)
        if: ${{ inputs.os == 'macos-latest' || inputs.os == 'ubuntu-latest' }}
        run: |
          chmod +x ./gradlew
          ./gradlew clean desktopApp:packageReleaseDistributionForCurrentOS | tee build.log
          file=$(grep desktopApp/build build.log | grep -v main-release/app | head -n 1 | awk '{print $NF}')
          path="openbible-desktop.${file##*.}"
          echo "path=$path" >> $GITHUB_ENV
          mv "$file" "$path"
      - name: Build Package (Windows)
        if: ${{ inputs.os == 'windows-latest' }}
        run: |
          chmod +x ./gradlew
          ./gradlew clean desktopApp:packageReleaseDistributionForCurrentOS | tee build.log
          $file=(cat build.log | findstr 'desktopApp\\build' | findstr -v 'main-release\\app' | head -n 1 | ForEach-Object { ($_.Split(' '))[-1] })
          $path="openbible-desktop.msi"
          echo "$path" >> $env:GITHUB_ENV
          mv "$file" "$path"
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.path }}
          path: ${{ env.path }}
